language: node_js
node_js:
  - "stable"
services:
 - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - createuser root
  - createdb codesling
install:
  - npm install
  - yarn install
script:
  - yarn
  - yarn buildEnv
  - yarn setup:rest-server
  - yarn setup:socket-server
  - yarn setup:services/coderunner-service
  - yarn db:setup:rest-server
  - yarn start
  - sleep 10  

